version: '3.9'

services:
  bot:
    build:
      context: src
      dockerfile: src/Dockerfile
    hostname: bot
    env_file:
      - ./.env
    environment:
      - SE_WEBDRIVER_URL=http://standalone-chrome:4444
      - REDIS_MASTER_HOST=redis
    volumes:
      - ./src/core:/app/core
      - ./src/bot:/app/bot
    depends_on:
      - redis
      - standalone-chrome
    restart: always
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis
    env_file:
      - ./.env
    ports:
      - "6379"
    restart: always
  standalone-chrome:
    image: selenium/standalone-chrome
    hostname: standalone-chrome
    environment:
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_SESSION_TIMEOUT=30
    ports:
      - "4440-4444:4440-4444"
    shm_size: '4g'
    restart: on-failure