version: '3.9'

services:
  bot:
    build:
      context: src
      dockerfile: bot.dockerfile
    hostname: bot
    env_file:
      - ./.env
    environment:
      - REDIS_MASTER_HOST=redis
    depends_on:
      - redis
    restart: always
  userbot:
    build:
      context: src
      dockerfile: userbot.dockerfile
    hostname: userbot
    env_file:
      - ./.env
    environment:
      - REDIS_MASTER_HOST=redis
    depends_on:
      - redis
    restart: always
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis
    ports:
      - "6379:6379"
    restart: always
  ngrok:
    image: shkoliar/ngrok:latest
    hostname: ngrok
    ports:
      - "4040:4040"
    env_file:
      - ./.env
    environment:
      - REGION=${REGION:-eu}
      - DOMAIN=telegram-bot
      - PORT=8000
    restart: "no"