version: '3.9'

services:
  bot:
    build:
      context: src
      dockerfile: bot.dockerfile
    hostname: bot
    env_file:
      - ./.env
    environment:
      - SE_WEBDRIVER_URL=http://standalone-chrome:4444
      - REDIS_MASTER_HOST=redis
    depends_on:
      - standalone-chrome
      - redis
    restart: always
    volumes:
      - ./src/core:/app/core
      - ./src/bot:/app/bot
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis
    env_file:
      - ./.env
    ports:
      - ${REDIS_MASTER_PORT_NUMBER}:6379
    restart: always
  standalone-chrome:
    image: selenium/standalone-chrome
    hostname: standalone-chrome
    environment:
      - SE_NODE_MAX_SESSIONS=3
#      - SE_SESSION_RETRY_INTERVAL=2
#      - SE_SESSION_REQUEST_TIMEOUT=600
#      - SE_NODE_SESSION_TIMEOUT=600
#      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "4440-4444:4440-4444"
    shm_size: '4g'
    restart: on-failure