version: '3.9'

services:
  bot:
    build:
      context: src
      dockerfile: bot.dockerfile
    hostname: bot
    env_file:
      - ./.env
    environment:
      - USERBOT_API_BASE_URL=http://userbot:8000
      - REDIS_MASTER_HOST=redis
    depends_on:
      - userbot
      - redis
    restart: always
    volumes:
      - ./src/core:/app/core
      - ./src/bot:/app/bot
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis
    ports:
      - "6379:6379"
    restart: always
  userbot:
    build:
      context: src
      dockerfile: userbot.dockerfile
    hostname: userbot
    env_file:
      - ./.env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - BACKEND_CORS_ORIGINS=["http://0.0.0.0"]
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always
    volumes:
      - ./src/core:/app/core
      - ./src/userbot:/app/userbot