version: '3.9'

services:
  bot:
    build:
      context: src
      dockerfile: bot.dockerfile
    hostname: bot
    env_file:
      - ./.env
    environment:
      - REDIS_MASTER_HOST=localhost
    depends_on:
      - redis
    restart: always
    volumes:
      - src/core:/app/core
      - src/bot:/app/bot
  userbot:
    build:
      context: src
      dockerfile: userbot.dockerfile
    hostname: userbot
    env_file:
      - ./.env
    depends_on:
      - redis
    restart: always
    volumes:
      - src/core:/app/core
      - src/userbot:/app/userbot
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis
    ports:
      - "6379:6379"
    restart: always