version: '3.9'

services:
  bot:
    build:
      context: src
      dockerfile: Dockerfile
    hostname: bot
    env_file:
      - ./.env
    environment:
      - SE_WEBDRIVER_URL=http://selenium-hub:4444
      - REDIS_MASTER_HOST=redis
    volumes:
      - ./src/core:/app/core
      - ./src/bot:/app/bot
    depends_on:
      - redis
    restart: always
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis
    env_file:
      - ./.env
    ports:
      - "6379"
    restart: always
