version: '3.9'

services:
  bot:
    build:
      context: src
      dockerfile: bot.dockerfile
    hostname: bot
    env_file:
      - ./.env
    environment:
      - REDIS_MASTER_HOST=redis
    depends_on:
      - selenium
      - redis
    restart: always
    volumes:
      - ./src/core:/app/core
      - ./src/bot:/app/bot
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - SE_SESSION_REQUEST_TIMEOUT=600
      - SE_SESSION_RETRY_INTERVAL=2
      - SE_NODE_SESSION_TIMEOUT=600
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - START_XVFB=false
    shm_size: '4g'
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis
    ports:
      - "6379:6379"
    restart: always